name: Record Orbit Stats
on:
  workflow_dispatch:
  schedule: # Run workflow automatically
    - cron: '0 1 * * 0' # Runs every Sunday at 1am

jobs:
  record-orbit-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Gather and record Orbit stats
        id: orbit-stats
        env:
          ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY }}
          ORBIT_WORKSPACE_ID: ${{ secrets.ORBIT_WORKSPACE_ID }}
          PGHOST: ${{ secrets.PGHOST }}
          PGUSER: ${{ secrets.PGUSER }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGPORT: ${{ secrets.PGPORT }}
        run: |
          cd ./actions/orbit-stats
          npm install
          npm run build
          node index.js